//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phnx.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phnx.Shared.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة معرف الإعلان.
        /// </summary>
        public static string ADVERTISEMENT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("ADVERTISEMENT_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإعلان غير موجود.
        /// </summary>
        public static string ADVERTISEMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ADVERTISEMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة معرف القسم.
        /// </summary>
        public static string DEPARTMENT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("DEPARTMENT_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة اسم القسم.
        /// </summary>
        public static string DEPARTMENT_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("DEPARTMENT_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم غير موجود.
        /// </summary>
        public static string DEPARTMENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("DEPARTMENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى كتابة البريد الإلكتروني.
        /// </summary>
        public static string EMPTY_EMAIL {
            get {
                return ResourceManager.GetString("EMPTY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى كتابة كلمة السر.
        /// </summary>
        public static string EMPTY_PASSWORD {
            get {
                return ResourceManager.GetString("EMPTY_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة تاريخ الحدث.
        /// </summary>
        public static string EVENT_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("EVENT_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة وصف الحدث.
        /// </summary>
        public static string EVENT_DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("EVENT_DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة معرف الحدث.
        /// </summary>
        public static string EVENT_ID_REQUIRED {
            get {
                return ResourceManager.GetString("EVENT_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة اسم الحدث.
        /// </summary>
        public static string EVENT_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("EVENT_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحدث غير موجود.
        /// </summary>
        public static string EVENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("EVENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة نوع الحدث.
        /// </summary>
        public static string EVENT_TYPE_REQUIRED {
            get {
                return ResourceManager.GetString("EVENT_TYPE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهت صلاحية الجلسة.
        /// </summary>
        public static string EXPIRED_SESSION {
            get {
                return ResourceManager.GetString("EXPIRED_SESSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة الصورة.
        /// </summary>
        public static string IMAGE_REQUIRED {
            get {
                return ResourceManager.GetString("IMAGE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الاعتماد غير صحيحة.
        /// </summary>
        public static string INVALID_CREDENTIALS {
            get {
                return ResourceManager.GetString("INVALID_CREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة وصف الوظيفة.
        /// </summary>
        public static string JOB_DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("JOB_DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة معرف الوظيفة.
        /// </summary>
        public static string JOB_ID_REQUIRED {
            get {
                return ResourceManager.GetString("JOB_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الوظيفة غير موجودة.
        /// </summary>
        public static string JOB_NOT_FOUND {
            get {
                return ResourceManager.GetString("JOB_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة عنوان الوظيفة.
        /// </summary>
        public static string JOB_TITLE_REQUIRED {
            get {
                return ResourceManager.GetString("JOB_TITLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة اسم جهة الاتصال.
        /// </summary>
        public static string LOST_ITEM_CONTACT_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("LOST_ITEM_CONTACT_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة رقم هاتف جهة الاتصال.
        /// </summary>
        public static string LOST_ITEM_CONTACT_PHONE_REQUIRED {
            get {
                return ResourceManager.GetString("LOST_ITEM_CONTACT_PHONE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة وصف العنصر المفقود.
        /// </summary>
        public static string LOST_ITEM_DESCRIPTION_REQUIRED {
            get {
                return ResourceManager.GetString("LOST_ITEM_DESCRIPTION_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة معرف العنصر المفقود.
        /// </summary>
        public static string LOST_ITEM_ID_REQUIRED {
            get {
                return ResourceManager.GetString("LOST_ITEM_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة اسم العنصر المفقود.
        /// </summary>
        public static string LOST_ITEM_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("LOST_ITEM_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العنصر المفقود غير موجود.
        /// </summary>
        public static string LOST_ITEM_NOT_FOUND {
            get {
                return ResourceManager.GetString("LOST_ITEM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم توفير رمز التحديث.
        /// </summary>
        public static string REFRESH_TOKEN_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("REFRESH_TOKEN_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم توفير الرمز المميز.
        /// </summary>
        public static string TOKEN_NOT_PROVIDED {
            get {
                return ResourceManager.GetString("TOKEN_NOT_PROVIDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني موجود بالفعل.
        /// </summary>
        public static string USER_EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني غير صحيح.
        /// </summary>
        public static string USER_EMAIL_INVALID {
            get {
                return ResourceManager.GetString("USER_EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة البريد الإلكتروني.
        /// </summary>
        public static string USER_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("USER_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة معرف المستخدم.
        /// </summary>
        public static string USER_ID_REQUIRED {
            get {
                return ResourceManager.GetString("USER_ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة اسم المستخدم.
        /// </summary>
        public static string USER_NAME_REQUIRED {
            get {
                return ResourceManager.GetString("USER_NAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخدم غير موجود.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجى إضافة كلمة السر.
        /// </summary>
        public static string USER_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("USER_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصلاحيات غير صحيحة.
        /// </summary>
        public static string USER_PERMISSIONS_INVALID {
            get {
                return ResourceManager.GetString("USER_PERMISSIONS_INVALID", resourceCulture);
            }
        }
    }
}
